import Head from "next/head";
import Image from "next/image";

export default function Home({ albums }) {
  console.log(albums);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div>
          <h3>hello</h3>
        </div>
      </>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=6`
  );
  const albums = await res.json();

  return {
    props: {
      albums,
    },
  };
};
