import Head from "next/head";
import Image from "next/image";
import clientPromise from "../lib/mongodb";

export default function Home({ blogs }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div>
          <h3>hello</h3>
        </div>

        <div>
          {blogs.map((blog, index) => {
            return (
              <div key={index}>
                <h2>{blog.title}</h2>
                <p>{blog.snippet}</p>
              </div>
            );
          })}
        </div>
      </>
    </div>
  );
}

export async function getServerSideProps(context) {
  const client = await clientPromise;

  const db = client.db("Cluster0");

  let blogs = await db.collection("blogs").find({}).toArray();
  blogs = JSON.parse(JSON.stringify(blogs));

  return {
    props: { blogs },
  };
}
